version: "3.4"

services:
  static-image:
    image: static-image-dev

    build:
      context: .
      target: development

    volumes:
      - ./:/app
      - /app/node_modules

    environment:
      - PORT=3000

    ports:
      - 3000:3000
      - 9229:9229
