name: STATIC
url: static.dedeard.my.id
title: STATIC
description: The CDN to speed up your images.
measurement_id: G-1TQYSY8SZ6

website_url: https://dedeard.my.id
repo_url: https://github.com/dedeard/static-image
github_url: https://github.com/dedeard
instagram_url: https://www.instagram.com/dedeard.js
linkedin_url: https://www.linkedin.com/in/dedeard
buymeacoffee_url: https://www.buymeacoffee.com/dedeard

twitter:
  username: _dedeard
  card: summary

facebook:
  app_id: 752472966269247
  admins: 100011972079252

author:
  name: Dede ardiansya
  url: https://dedeard.my.id

social:
  name: Dede ardiansya
  links:
    - https://dedeard.my.id
    - https://twitter.com/_dedeard
    - https://www.facebook.com/dedeard.ts
    - https://www.linkedin.com/in/dedeard
    - https://github.com/dedeard
    - https://www.instagram.com/dedeard.js

plugins:
  - jekyll-seo-tag

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - tailwind.css